---
- name: Install Node Exporter
  apt:
    name: prometheus-node-exporter
    state: present

- name: Ensure Node Exporter is running
  service:
    name: prometheus-node-exporter
    state: started
    enabled: yes

- name: Install SNMP Exporter
  apt:
    name: prometheus-snmp-exporter
    state: present

- name: Create SNMP exporter config directory
  file:
    path: /etc/snmp_exporter
    state: directory
    owner: root
    group: root
    mode: '0755'
  register: snmp_dir

- name: Create empty config file if needed
  file:
    path: /etc/snmp_exporter/snmp.yml
    state: touch
    owner: root
    group: root
    mode: '0644'

- name: Configure SNMP Exporter
  template:
    src: snmp.yml.j2
    dest: /etc/snmp_exporter/snmp.yml
    owner: root
    group: root
    mode: '0644'
  notify: restart snmp-exporter

- name: Ensure SNMP exporter is enabled and running
  service:
    name: prometheus-snmp-exporter
    state: started
    enabled: yes