---
- name: Install Prometheus components
  include_tasks: prometheus.yml
  tags: prometheus

- name: Install and configure exporters
  include_tasks: exporters.yml
  tags: exporters

- name: Configure Grafana
  include_tasks: grafana.yml
  tags: grafana

- name: Verify services are running
  block:
    - name: Check Prometheus status
      uri:
        url: "http://localhost:9090/-/healthy"
        return_content: yes
      register: prometheus_health
      until: "'Prometheus is Healthy' in prometheus_health.content"
      retries: 5
      delay: 10

    - name: Check Grafana status
      uri:
        url: "http://localhost:3000/api/health"
        return_content: yes
      register: grafana_health
      until: "'OK' in grafana_health.content"
      retries: 10
      delay: 10
      when: grafana_enabled | default(true)