---
- name: Apply base configuration to all nodes
  hosts: servers
  become: true
  gather_facts: true
  vars_files:
    - ~/ansible/inventories/dev/group_vars/secrets.yml
  roles:
    - server_config